/**
 * Created by yijaejun on 07/03/2017.
 */
module.exports = {
	INTERNAL_ERROR : 'INTERNAL_ERROR',
	NO_ACCOUNT : 'NO_ACCOUNT',
	LOGIN_FAILED_WARNING : 'LOGIN_FAILED_WARNING',
	PASSWORD_NOT_MATCHED : 'PASSWORD_NOT_MATCHED',
	BANNED : 'BANNED',
	LOGIN_FAILED_EXCEED : 'LOGIN_FAILED_EXCEED',
	LOGIN_SUCCESS : 'LOGIN_SUCCESS',
	WRONG_ACCESS : 'WRONG_ACCESS',
	UNKNOWN_ERROR : 'UNKNOWN_ERROR'
};