module.exports = {
	WRONG_ACCESS : '잘못된 접근입니다.'

	// LOGIN_ERROR : {
	// 	INTERNAL_ERROR : 'INTERNAL_ERROR',
	// 	NO_ACCOUNT : 'NO_ACCOUNT',
	// 	LOGIN_FAILED_WARNING : 'LOGIN_FAILED_WARNING',
	// 	PASSWORD_NOT_MATCHED : 'PASSWORD_NOT_MATCHED',
	// 	BANNED : 'BANNED',
	// 	LOGIN_FAILED_EXCEED : 'LOGIN_FAILED_EXCEED',
	// 	LOGIN_SUCCESS : 'LOGIN_SUCCESS'
	// }
};